sudo: required
services:
        - docker

before_install:
        - docker build -t vipulk/docker-react -f Dockerfile.dev .

script:
        - docker run -e language=generic CI=true vipulk/docker-react npm run test
