version: '3'
services:
        web:
                stdin_open: true
                build:
                        context: .
                        dockerfile: Docker.dev
                ports:
                        - "3000:3000"
                volumes:
                        - /app/app_modules
                        - .:/app
